[deploy]
startCommand = "php artisan config:clear && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"

[build]
buildCommand = "composer install --no-dev --optimize-autoloader"
